name: .NET Build and Test

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  build:
    runs-on: windows-latest

    env:
      Solution_Name: BerryAIGen.sln
      DotNet_Version: '8.0.x'

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DotNet_Version }}

    - name: Restore dependencies
      run: dotnet restore ${{ env.Solution_Name }}

    - name: Build
      run: dotnet build ${{ env.Solution_Name }} --configuration Release --no-restore

    - name: Test
      run: dotnet test ${{ env.Solution_Name }} --configuration Release --no-build --verbosity normal

  build-linux:
    runs-on: ubuntu-latest

    env:
      Solution_Name: BerryAIGen.sln
      DotNet_Version: '8.0.x'

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DotNet_Version }}

    - name: Restore dependencies
      run: dotnet restore ${{ env.Solution_Name }}

    - name: Build
      run: dotnet build ${{ env.Solution_Name }} --configuration Release --no-restore

    - name: Test
      run: dotnet test ${{ env.Solution_Name }} --configuration Release --no-build --verbosity normal

  build-macos:
    runs-on: macos-latest

    env:
      Solution_Name: BerryAIGen.sln
      DotNet_Version: '8.0.x'

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DotNet_Version }}

    - name: Restore dependencies
      run: dotnet restore ${{ env.Solution_Name }}

    - name: Build
      run: dotnet build ${{ env.Solution_Name }} --configuration Release --no-restore

    - name: Test
      run: dotnet test ${{ env.Solution_Name }} --configuration Release --no-build --verbosity normal